workspace 'FBTNetworking.xcworkspace'
platform :ios, '8.0'

############################################################
#0、FBTNetworkingDemo
project 'FBTNetworkingDemo/FBTNetworkingDemo.xcodeproj'
#1、FBTNetworking
project 'FBTNetworking/FBTNetworking.xcodeproj'

############################################################
#0、FBTNetworkingDemo
target 'FBTNetworkingDemo' do
platform :ios, '8.0'
project 'FBTNetworkingDemo/FBTNetworkingDemo.xcodeproj'
pod 'AFNetworking', '~>3.0'
pod 'MJExtension', '~>3.0'
pod 'FBTNetProtocol', :git => 'https://git.coding.net/FBlife/FBTNetProtocol.git'
end

#1、FBTNetworking
target 'FBTNetworking' do
platform :ios, '8.0'
project 'FBTNetworking/FBTNetworking.xcodeproj'
pod ‘AFNetworking’, '~>3.0'
pod 'MJExtension', '~>3.0'
pod 'FBTNetProtocol', :git => 'https://git.coding.net/FBlife/FBTNetProtocol.git'

end
